FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache tini

COPY package*.json ./
RUN npm ci

COPY . .

RUN chmod +x docker-entrypoint.sh

ENV NODE_ENV=development

EXPOSE 3000

ENTRYPOINT ["/sbin/tini", "--", "./docker-entrypoint.sh"]
CMD ["npm", "run", "dev"]
