/**
 * Realistic Bulgarian-market rental fleet (20 cars).
 *
 * All registration numbers and VINs in this file are fictional test/demo
 * identifiers. They are not issued plates, not real chassis numbers, and
 * must not be treated as production vehicle identity data.
 *
 * Persistable columns match `cars` (see sql/schema/002_cars.sql). Extra
 * keys (year, color, bodyType, doors, luggage, engine, equipment) are for
 * review only — the schema has no matching columns.
 *
 * Prices are NUMERIC(10,2) EUR major units (pricing engine + Stripe `eur`).
 * Suggested BGN day rates are stored as the same numbers in EUR, per product
 * decision. Weekly/long-stay rates use price_tier_7_31 / price_tier_31_plus
 * (~82% / ~72% of the 1–3 day rate, matching existing demo cars). Deposit
 * is global (`pricing_deposit_rules`, default 300 EUR), not per car.
 */

const PLACEHOLDER_IMAGE = '/placeholder-car.svg';

const REALISTIC_FLEET_CATEGORIES = ['Economy', 'Compact', 'SUV', 'Van'];

/**
 * VIN-like 17-character values using a clearly fake WMI (`ZZ1`) and no I/O/Q.
 * Pattern: ZZ1RACV3SEED00 + zero-padded 001..020
 */
function fictionalVin(seq) {
  return `ZZ1RACV3SEED00${String(seq).padStart(3, '0')}`;
}

function fictionalPlate(seq) {
  return `C ${1000 + seq} XX`;
}

const REALISTIC_FLEET = [
  {
    seq: 1,
    name: 'Dacia Sandero',
    year: 2023,
    categoryName: 'Economy',
    bodyType: 'hatchback',
    color: 'White',
    doors: 5,
    luggage: '1 large + 1 cabin',
    engine: '1.0 TCe 90 hp',
    transmission: 'Manual',
    fuelType: 'Petrol',
    seats: 5,
    price: 65.0,
    pricePerDay: 53.0,
    priceTier_1_3: 65.0,
    priceTier_7_31: 53.0,
    priceTier_31_plus: 47.0,
    registrationNumber: fictionalPlate(1),
    vin: fictionalVin(1),
    mileage: 28400,
    fuelLevel: 'full',
    currentLocation: 'Sofia',
    insuranceExpiry: '2027-11-30',
    technicalInspectionExpiry: '2027-06-15',
    image: PLACEHOLDER_IMAGE,
    equipment: ['A/C', 'Bluetooth', 'USB', 'Child-seat ISOFIX'],
  },
  {
    seq: 2,
    name: 'Renault Clio',
    year: 2024,
    categoryName: 'Economy',
    bodyType: 'hatchback',
    color: 'Grey',
    doors: 5,
    luggage: '1 large + 1 cabin',
    engine: '1.0 TCe 90 hp',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    seats: 5,
    price: 70.0,
    pricePerDay: 57.0,
    priceTier_1_3: 70.0,
    priceTier_7_31: 57.0,
    priceTier_31_plus: 50.0,
    registrationNumber: fictionalPlate(2),
    vin: fictionalVin(2),
    mileage: 19250,
    fuelLevel: 'full',
    currentLocation: 'Sofia Airport',
    insuranceExpiry: '2027-10-31',
    technicalInspectionExpiry: '2027-05-20',
    image: PLACEHOLDER_IMAGE,
    equipment: ['A/C', 'Bluetooth', 'Android Auto', 'Apple CarPlay', 'USB', 'Rear sensors'],
  },
  {
    seq: 3,
    name: 'Toyota Aygo',
    year: 2022,
    categoryName: 'Economy',
    bodyType: 'mini hatchback',
    color: 'Red',
    doors: 5,
    luggage: '2 cabin bags',
    engine: '1.0 VVT-i 72 hp',
    transmission: 'Manual',
    fuelType: 'Petrol',
    seats: 5,
    price: 60.0,
    pricePerDay: 49.0,
    priceTier_1_3: 60.0,
    priceTier_7_31: 49.0,
    priceTier_31_plus: 43.0,
    registrationNumber: fictionalPlate(3),
    vin: fictionalVin(3),
    mileage: 41200,
    fuelLevel: 'full',
    currentLocation: 'Sunny Beach',
    insuranceExpiry: '2027-09-30',
    technicalInspectionExpiry: '2027-04-10',
    image: PLACEHOLDER_IMAGE,
    equipment: ['A/C', 'Bluetooth', 'USB'],
  },
  {
    seq: 4,
    name: 'Hyundai i10',
    year: 2023,
    categoryName: 'Economy',
    bodyType: 'mini hatchback',
    color: 'Blue',
    doors: 5,
    luggage: '2 cabin bags',
    engine: '1.0 67 hp',
    transmission: 'Manual',
    fuelType: 'Petrol',
    seats: 5,
    price: 60.0,
    pricePerDay: 49.0,
    priceTier_1_3: 60.0,
    priceTier_7_31: 49.0,
    priceTier_31_plus: 43.0,
    registrationNumber: fictionalPlate(4),
    vin: fictionalVin(4),
    mileage: 33800,
    fuelLevel: 'full',
    currentLocation: 'Burgas Airport',
    insuranceExpiry: '2027-12-15',
    technicalInspectionExpiry: '2027-07-01',
    image: PLACEHOLDER_IMAGE,
    equipment: ['A/C', 'Bluetooth', 'Apple CarPlay', 'USB', 'Child-seat ISOFIX'],
  },
  {
    seq: 5,
    name: 'Kia Picanto',
    year: 2021,
    categoryName: 'Economy',
    bodyType: 'mini hatchback',
    color: 'Yellow',
    doors: 5,
    luggage: '2 cabin bags',
    engine: '1.0 67 hp',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    seats: 5,
    price: 62.0,
    pricePerDay: 51.0,
    priceTier_1_3: 62.0,
    priceTier_7_31: 51.0,
    priceTier_31_plus: 45.0,
    registrationNumber: fictionalPlate(5),
    vin: fictionalVin(5),
    mileage: 52100,
    fuelLevel: 'full',
    currentLocation: 'Varna',
    insuranceExpiry: '2027-08-31',
    technicalInspectionExpiry: '2027-03-18',
    image: PLACEHOLDER_IMAGE,
    equipment: ['A/C', 'Bluetooth', 'USB', 'Rear sensors'],
  },
  {
    seq: 6,
    name: 'Volkswagen Polo',
    year: 2024,
    categoryName: 'Economy',
    bodyType: 'hatchback',
    color: 'Silver',
    doors: 5,
    luggage: '1 large + 1 cabin',
    engine: '1.0 TSI 95 hp',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    seats: 5,
    price: 75.0,
    pricePerDay: 62.0,
    priceTier_1_3: 75.0,
    priceTier_7_31: 62.0,
    priceTier_31_plus: 54.0,
    registrationNumber: fictionalPlate(6),
    vin: fictionalVin(6),
    mileage: 15400,
    fuelLevel: 'full',
    currentLocation: 'Sofia Airport',
    insuranceExpiry: '2028-01-31',
    technicalInspectionExpiry: '2027-08-22',
    image: PLACEHOLDER_IMAGE,
    equipment: [
      'A/C',
      'Bluetooth',
      'Android Auto',
      'Apple CarPlay',
      'Cruise control',
      'Rear camera',
      'USB',
    ],
  },
  {
    seq: 7,
    name: 'Opel Corsa',
    year: 2022,
    categoryName: 'Economy',
    bodyType: 'hatchback',
    color: 'Black',
    doors: 5,
    luggage: '1 large + 1 cabin',
    engine: '1.2 75 hp',
    transmission: 'Manual',
    fuelType: 'Petrol',
    seats: 5,
    price: 68.0,
    pricePerDay: 56.0,
    priceTier_1_3: 68.0,
    priceTier_7_31: 56.0,
    priceTier_31_plus: 49.0,
    registrationNumber: fictionalPlate(7),
    vin: fictionalVin(7),
    mileage: 36750,
    fuelLevel: 'full',
    currentLocation: 'Plovdiv',
    insuranceExpiry: '2027-07-31',
    technicalInspectionExpiry: '2027-02-28',
    image: PLACEHOLDER_IMAGE,
    equipment: ['A/C', 'Bluetooth', 'Android Auto', 'USB', 'Rear sensors', 'Child-seat ISOFIX'],
  },
  {
    seq: 8,
    name: 'Peugeot 208',
    year: 2023,
    categoryName: 'Economy',
    bodyType: 'hatchback',
    color: 'Orange',
    doors: 5,
    luggage: '1 large + 1 cabin',
    engine: '1.2 PureTech 100 hp',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    seats: 5,
    price: 72.0,
    pricePerDay: 59.0,
    priceTier_1_3: 72.0,
    priceTier_7_31: 59.0,
    priceTier_31_plus: 52.0,
    registrationNumber: fictionalPlate(8),
    vin: fictionalVin(8),
    mileage: 22100,
    fuelLevel: 'full',
    currentLocation: 'Office',
    insuranceExpiry: '2027-11-15',
    technicalInspectionExpiry: '2027-06-30',
    image: PLACEHOLDER_IMAGE,
    equipment: ['A/C', 'Bluetooth', 'Android Auto', 'Apple CarPlay', 'Cruise control', 'USB'],
  },
  {
    seq: 9,
    name: 'Renault Captur',
    year: 2024,
    categoryName: 'SUV',
    bodyType: 'compact SUV',
    color: 'Orange',
    doors: 5,
    luggage: '2 large',
    engine: '1.3 TCe 140 hp',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    seats: 5,
    price: 105.0,
    pricePerDay: 86.0,
    priceTier_1_3: 105.0,
    priceTier_7_31: 86.0,
    priceTier_31_plus: 76.0,
    registrationNumber: fictionalPlate(9),
    vin: fictionalVin(9),
    mileage: 18700,
    fuelLevel: 'full',
    currentLocation: 'Sofia',
    insuranceExpiry: '2028-02-28',
    technicalInspectionExpiry: '2027-09-12',
    image: PLACEHOLDER_IMAGE,
    equipment: [
      'A/C',
      'Bluetooth',
      'Android Auto',
      'Apple CarPlay',
      'Cruise control',
      'Rear camera',
      'Rear sensors',
      'USB',
      'Child-seat ISOFIX',
    ],
  },
  {
    seq: 10,
    name: 'Dacia Duster',
    year: 2023,
    categoryName: 'SUV',
    bodyType: 'SUV',
    color: 'Khaki',
    doors: 5,
    luggage: '2 large + 1 cabin',
    engine: '1.5 Blue dCi 115 hp',
    transmission: 'Manual',
    fuelType: 'Diesel',
    seats: 5,
    price: 110.0,
    pricePerDay: 90.0,
    priceTier_1_3: 110.0,
    priceTier_7_31: 90.0,
    priceTier_31_plus: 79.0,
    registrationNumber: fictionalPlate(10),
    vin: fictionalVin(10),
    mileage: 30500,
    fuelLevel: 'full',
    currentLocation: 'Burgas',
    insuranceExpiry: '2027-10-15',
    technicalInspectionExpiry: '2027-05-05',
    image: PLACEHOLDER_IMAGE,
    equipment: ['A/C', 'Bluetooth', 'Cruise control', 'Rear sensors', 'USB', 'Child-seat ISOFIX'],
  },
  {
    seq: 11,
    name: 'Nissan Juke',
    year: 2022,
    categoryName: 'SUV',
    bodyType: 'compact SUV',
    color: 'White',
    doors: 5,
    luggage: '2 large',
    engine: '1.0 DIG-T 114 hp',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    seats: 5,
    price: 115.0,
    pricePerDay: 94.0,
    priceTier_1_3: 115.0,
    priceTier_7_31: 94.0,
    priceTier_31_plus: 83.0,
    registrationNumber: fictionalPlate(11),
    vin: fictionalVin(11),
    mileage: 44800,
    fuelLevel: 'full',
    currentLocation: 'Varna Airport',
    insuranceExpiry: '2027-09-01',
    technicalInspectionExpiry: '2027-04-22',
    image: PLACEHOLDER_IMAGE,
    equipment: [
      'A/C',
      'Bluetooth',
      'Android Auto',
      'Apple CarPlay',
      'Cruise control',
      'Rear camera',
      'USB',
    ],
  },
  {
    seq: 12,
    name: 'Volkswagen T-Cross',
    year: 2025,
    categoryName: 'SUV',
    bodyType: 'compact SUV',
    color: 'Blue',
    doors: 5,
    luggage: '2 large',
    engine: '1.0 TSI 110 hp',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    seats: 5,
    price: 120.0,
    pricePerDay: 98.0,
    priceTier_1_3: 120.0,
    priceTier_7_31: 98.0,
    priceTier_31_plus: 86.0,
    registrationNumber: fictionalPlate(12),
    vin: fictionalVin(12),
    mileage: 8900,
    fuelLevel: 'full',
    currentLocation: 'Sofia Airport',
    insuranceExpiry: '2028-03-31',
    technicalInspectionExpiry: '2027-10-08',
    image: PLACEHOLDER_IMAGE,
    equipment: [
      'A/C',
      'Bluetooth',
      'Android Auto',
      'Apple CarPlay',
      'Cruise control',
      'Rear camera',
      'Rear sensors',
      'USB',
      'Child-seat ISOFIX',
    ],
  },
  {
    seq: 13,
    name: 'Skoda Kamiq',
    year: 2024,
    categoryName: 'SUV',
    bodyType: 'compact SUV',
    color: 'Grey',
    doors: 5,
    luggage: '2 large',
    engine: '1.0 TSI 110 hp',
    transmission: 'Manual',
    fuelType: 'Petrol',
    seats: 5,
    price: 115.0,
    pricePerDay: 94.0,
    priceTier_1_3: 115.0,
    priceTier_7_31: 94.0,
    priceTier_31_plus: 83.0,
    registrationNumber: fictionalPlate(13),
    vin: fictionalVin(13),
    mileage: 17600,
    fuelLevel: 'full',
    currentLocation: 'Nesebar',
    insuranceExpiry: '2028-01-15',
    technicalInspectionExpiry: '2027-08-01',
    image: PLACEHOLDER_IMAGE,
    equipment: ['A/C', 'Bluetooth', 'Android Auto', 'Apple CarPlay', 'Cruise control', 'USB'],
  },
  {
    seq: 14,
    name: 'Toyota Corolla',
    year: 2023,
    categoryName: 'Compact',
    bodyType: 'sedan/hatchback',
    color: 'White',
    doors: 5,
    luggage: '2 large',
    engine: '1.8 Hybrid 140 hp',
    transmission: 'Automatic',
    fuelType: 'Hybrid',
    seats: 5,
    price: 100.0,
    pricePerDay: 82.0,
    priceTier_1_3: 100.0,
    priceTier_7_31: 82.0,
    priceTier_31_plus: 72.0,
    registrationNumber: fictionalPlate(14),
    vin: fictionalVin(14),
    mileage: 26300,
    fuelLevel: 'full',
    currentLocation: 'Sofia',
    insuranceExpiry: '2027-12-31',
    technicalInspectionExpiry: '2027-07-20',
    image: PLACEHOLDER_IMAGE,
    equipment: [
      'A/C',
      'Bluetooth',
      'Android Auto',
      'Apple CarPlay',
      'Cruise control',
      'Rear camera',
      'USB',
      'Child-seat ISOFIX',
    ],
  },
  {
    seq: 15,
    name: 'Volkswagen Golf',
    year: 2022,
    categoryName: 'Compact',
    bodyType: 'hatchback',
    color: 'Black',
    doors: 5,
    luggage: '2 large',
    engine: '1.5 TSI 130 hp',
    transmission: 'Manual',
    fuelType: 'Petrol',
    seats: 5,
    price: 95.0,
    pricePerDay: 78.0,
    priceTier_1_3: 95.0,
    priceTier_7_31: 78.0,
    priceTier_31_plus: 68.0,
    registrationNumber: fictionalPlate(15),
    vin: fictionalVin(15),
    mileage: 48900,
    fuelLevel: 'full',
    currentLocation: 'Office',
    insuranceExpiry: '2027-08-20',
    technicalInspectionExpiry: '2027-03-11',
    image: PLACEHOLDER_IMAGE,
    equipment: ['A/C', 'Bluetooth', 'Android Auto', 'Apple CarPlay', 'Cruise control', 'USB'],
  },
  {
    seq: 16,
    name: 'Skoda Octavia',
    year: 2024,
    categoryName: 'Compact',
    bodyType: 'sedan/wagon',
    color: 'Silver',
    doors: 5,
    luggage: '3 large',
    engine: '2.0 TDI 150 hp',
    transmission: 'Automatic',
    fuelType: 'Diesel',
    seats: 5,
    price: 105.0,
    pricePerDay: 86.0,
    priceTier_1_3: 105.0,
    priceTier_7_31: 86.0,
    priceTier_31_plus: 76.0,
    registrationNumber: fictionalPlate(16),
    vin: fictionalVin(16),
    mileage: 21400,
    fuelLevel: 'full',
    currentLocation: 'Plovdiv',
    insuranceExpiry: '2028-02-15',
    technicalInspectionExpiry: '2027-09-25',
    image: PLACEHOLDER_IMAGE,
    equipment: [
      'A/C',
      'Bluetooth',
      'Android Auto',
      'Apple CarPlay',
      'Cruise control',
      'Rear camera',
      'Rear sensors',
      'USB',
      'Child-seat ISOFIX',
    ],
  },
  {
    seq: 17,
    name: 'Toyota Corolla Touring Sports',
    year: 2025,
    categoryName: 'Compact',
    bodyType: 'estate',
    color: 'Grey',
    doors: 5,
    luggage: '3 large',
    engine: '1.8 Hybrid 140 hp',
    transmission: 'Automatic',
    fuelType: 'Hybrid',
    seats: 5,
    price: 120.0,
    pricePerDay: 98.0,
    priceTier_1_3: 120.0,
    priceTier_7_31: 98.0,
    priceTier_31_plus: 86.0,
    registrationNumber: fictionalPlate(17),
    vin: fictionalVin(17),
    mileage: 11200,
    fuelLevel: 'full',
    currentLocation: 'Sofia Airport',
    insuranceExpiry: '2028-04-30',
    technicalInspectionExpiry: '2027-11-14',
    image: PLACEHOLDER_IMAGE,
    equipment: [
      'A/C',
      'Bluetooth',
      'Android Auto',
      'Apple CarPlay',
      'Cruise control',
      'Rear camera',
      'USB',
      'Child-seat ISOFIX',
    ],
  },
  {
    seq: 18,
    name: 'Renault Megane Grandtour',
    year: 2021,
    categoryName: 'Compact',
    bodyType: 'estate',
    color: 'Blue',
    doors: 5,
    luggage: '3 large',
    engine: '1.5 Blue dCi 115 hp',
    transmission: 'Manual',
    fuelType: 'Diesel',
    seats: 5,
    price: 110.0,
    pricePerDay: 90.0,
    priceTier_1_3: 110.0,
    priceTier_7_31: 90.0,
    priceTier_31_plus: 79.0,
    registrationNumber: fictionalPlate(18),
    vin: fictionalVin(18),
    mileage: 61200,
    fuelLevel: 'full',
    currentLocation: 'Burgas Airport',
    insuranceExpiry: '2027-06-30',
    technicalInspectionExpiry: '2027-01-20',
    image: PLACEHOLDER_IMAGE,
    equipment: ['A/C', 'Bluetooth', 'Cruise control', 'Rear sensors', 'USB', 'Child-seat ISOFIX'],
  },
  {
    seq: 19,
    name: 'Volkswagen Touran',
    year: 2022,
    categoryName: 'Van',
    bodyType: '7-seat MPV',
    color: 'Silver',
    doors: 5,
    luggage: '2 large with 7 seats',
    engine: '1.5 TSI 150 hp',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    seats: 7,
    price: 135.0,
    pricePerDay: 111.0,
    priceTier_1_3: 135.0,
    priceTier_7_31: 111.0,
    priceTier_31_plus: 97.0,
    registrationNumber: fictionalPlate(19),
    vin: fictionalVin(19),
    mileage: 39800,
    fuelLevel: 'full',
    currentLocation: 'Varna',
    insuranceExpiry: '2027-11-01',
    technicalInspectionExpiry: '2027-06-08',
    image: PLACEHOLDER_IMAGE,
    equipment: [
      'A/C',
      'Bluetooth',
      'Android Auto',
      'Apple CarPlay',
      'Cruise control',
      'Rear camera',
      'USB',
      'Child-seat ISOFIX',
    ],
  },
  {
    seq: 20,
    name: 'Mercedes-Benz Vito',
    year: 2024,
    categoryName: 'Van',
    bodyType: 'passenger van',
    color: 'Black',
    doors: 4,
    luggage: '4 large behind last row',
    engine: '2.0 CDI 163 hp',
    transmission: 'Automatic',
    fuelType: 'Diesel',
    seats: 8,
    price: 190.0,
    pricePerDay: 156.0,
    priceTier_1_3: 190.0,
    priceTier_7_31: 156.0,
    priceTier_31_plus: 137.0,
    registrationNumber: fictionalPlate(20),
    vin: fictionalVin(20),
    mileage: 24500,
    fuelLevel: 'full',
    currentLocation: 'Sofia Airport',
    insuranceExpiry: '2028-05-31',
    technicalInspectionExpiry: '2027-12-01',
    image: PLACEHOLDER_IMAGE,
    equipment: [
      'A/C',
      'Bluetooth',
      'Android Auto',
      'Apple CarPlay',
      'Cruise control',
      'Rear camera',
      'Rear sensors',
      'USB',
      'Child-seat ISOFIX',
    ],
  },
];

module.exports = {
  PLACEHOLDER_IMAGE,
  REALISTIC_FLEET,
  REALISTIC_FLEET_CATEGORIES,
  fictionalVin,
  fictionalPlate,
};
